### ISSUE TITLE
About the example of usage

### ISSUE THREAD

**Issue by keding-com** [php-sap/saprfc-kralik#4]
HI, gregor-j

I follow your project description to do on my project to test the example.
But I always can not get correct output result.

I use this page example [https://php-sap.github.io/saprfc-function](https://php-sap.github.io/saprfc-function)
If I do not use the part of code
```
$inputDate = new DateTime('2019-12-31');
$function->setParams([
    'IV_DATE' => $inputDate->format(SapDateTime::SAP_DATE)
]);
```
result is 
```
phpsap\saprfc\SapRfc {
  -connection: null
  -function: null
  #config: phpsap\classes\Config\ConfigTypeA {
    -data: {
      +"ashost": "192.168.1.213:3300"
      +"sysnr": "01"
      +"user": "itrfc"
      +"passwd": "******"
      +"client": "600"
    }
  }
  -name: "ZSD_DELIVERY_DATA"
  -data: {#99}
```
else I use then get `Configuration is missing!` error message

I try to connection my company SAP function in first time, so I have no idea about connection SAP. I guess maybe some configuration not turn on.
And I watch [php7-sapnwrfc.readthedocs.io](https://php7-sapnwrfc.readthedocs.io) before, and I install finished, and sapnwrfc extension is enable on my phpinfo()

- Questions
 1. The  `ZSD_DELIVERY_DATA` is my company SAP function name, and setParams() is for that? so I have to use that function params ?
2. If I want to connection my company SAP function get something, I should care what kind of configuration on SAP, can you give me some suggestions?
3. Why me output not like your example?

I hope you can reply my questions.

Thank you

-----
other questions

I use POSTMAN send request, and get `Error: socket hang up`, I don't know how to resolve it

**Comment by gregor-j** [comment]
First of all: There was a typo in the example on https://php-sap.github.io/saprfc-function. I corrected that.

Regarding your questions:
1. Yes, `setParams()` is for setting input parameters of the SAP remote function (`ZSD_DELIVERY_DATA` in your case).
2. As I mentioned, there is a typo in the example. You have to provide connection settings (ashost, sysnr, etc.) _before_ setting parameters, because `setParams()` will try to check the whether the input parameter names exist.
3. `json_encoding()` a SAP remote function call will just create a JSON representation of that function call, but not actually call the SAP remote function.

I don't know the `ZSD_DELIVERY_DATA` SAP remote function. The the name of the SAP remote function and the name and type of the input and output parameters are defined by the person that programmed your SAP remote function.

Let's assume you have a SAP remote function called `ZZZ_ADDITION` with two input parameters called `INPUT_A` and `INPUT_B` and one output parameter called `OUTPUT_RESULT`. The API of this imaginary `ZZZ_ADDITION` would look something like this:

```json
[
    {
      "type": "int",
      "name": "INPUT_A",
      "direction": "input",
      "optional": false
    },
    {
      "type": "int",
      "name": "INPUT_B",
      "direction": "input",
      "optional": false
    },
    {
      "type": "int",
      "name": "OUTPUT_RESULT",
      "direction": "output",
      "optional": false
    }
]
```

```php
//define your SAP connection data
$connectionConfig = new ConfigTypeA([
      ConfigTypeA::JSON_ASHOST => '192.168.1.213',
      ConfigTypeA::JSON_SYSNR  => '01',
      ConfigTypeA::JSON_CLIENT => '600',
      ConfigTypeA::JSON_USER   => 'itrfc',
      ConfigTypeA::JSON_PASSWD => '************'
  ]);
//create an instance of SapRfc for your remote function
$function = new SapRfc('ZZZ_ADDITION');
//apply the configuration
$function->setConfiguration($connectionConfig);
//set the input parameters of your remote function
$function->setParams([
    'INPUT_A' => '3',
    'INPUT_B' => '2'
]);
//call the SAP remote function ZZZ_ADDITION and get the result
$result = $function->invoke();
//echo the output parameter
echo $result['OUTPUT_RESULT'];
```

**Comment by keding-com** [comment]
Thank you very much, I will try again
