### ISSUE TITLE
add support for gkralik/php7-sapnwrfc v2.0

### ISSUE THREAD

**Issue by gregor-j** [php-sap/saprfc-kralik#6]
see https://github.com/gkralik/php7-sapnwrfc/releases/tag/2.0.0-beta1 for breaking changes

**Comment by ynnoig** [comment]
Any news about the support for gkralik/php7-sapnwrfc v2.X ?

**Comment by gregor-j** [comment]
I'm a bit overloaded with my day-job and currently don't have the time.

**Comment by ynnoig** [comment]
Hi @gregor-j 

I noticed that this issue still remained inactive and that the library still does not support gkralik v.2.

Possibly I can help you in collaborating and migrating the application in making it compatible with v.2 of kralik. 

Do you have a list of all the Breaking changes or what would need to be updated? So that I can get an idea on what to do and consider possible collaboration through a PR.

Thank you,
Gio

**Comment by gregor-j** [comment]
this issue has been resolved by #19
